modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="customquests" #mandatory
version="1.14.4-1.0.0" #mandatory
displayName="Custom Quests" #mandatory
description='''
Quests!!!
'''