modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="customquests" #mandatory
version="1.14.4-0.1-DEV1" #mandatory
displayName="Custom Quests" #mandatory
description='''
Quests!!!
'''